version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
  api:
    container_name: go-app
    build:
      context: ./
      target: production
    image:  go-app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    links:
      - db
volumes:
  db:
    driver: local